FROM centos:latest

# install depedencies
RUN dnf update -y && \
	dnf install epel-release -y && \
	dnf install 'dnf-command(config-manager)' -y && \
	dnf config-manager --set-enabled powertools -y && \
	dnf update -y && \
	dnf install gcc gcc-c++ glibc-devel make which git wget flex bison gperf python39 cmake ninja-build ccache -y && \
	dnf clean all

# clone esp-idf
RUN mkdir /esp && cd /esp && \
  git clone -b v4.3 --recursive https://github.com/espressif/esp-idf.git && \ 
  git -C esp-idf/ checkout v4.3 && \
  git -C esp-idf submodule update --init \ 
    components/bt/host/nimble/nimble \ 
    components/esp_wifi \ 
    components/esptool_py/esptool \
    components/lwip/lwip \ 
    components/mbedtls/mbedtls \
    components/bt/controller/lib_esp32 \
    components/bt/controller/lib_esp32c3_family

# set up environment
RUN export PATH="$PATH:/root/.local/bin/" && /esp/esp-idf/install.sh

# clone micropython
RUN source /esp/esp-idf/export.sh && \
  cd /esp && \
  git clone -b v1.16 https://github.com/micropython/micropython && \ 
  git -C micropython/ checkout v1.16

# build micropython cross-compiler
RUN source /esp/esp-idf/export.sh && make -C /esp/micropython/mpy-cross 
